# baseURL = 'https://kamar535.github.io/idt-deploy-test.github.io/'

defaultContentLanguage = 'sv'

# https://mcshelby.github.io/hugo-theme-relearn/configuration/sitemanagement/deployment/index.html#public-web-server-from-subdirectory
relativeURLs = false

# languageCode = 'en-us'
# languageCode = 'de-DE'
#title = 'Introduktion till datorer 2025'

# Do not set theme here when using modules. 

# Modules on the bottom will get loaded first, so keep anything you don’t want
# overridden higher up in the module chain. All conflicting files during module
# import will use the last file loaded. 


[params]
    # # https://github.com/McShelby/hugo-theme-relearn/issues/882
    useDefaultRelref = true
    # https://mcshelby.github.io/hugo-theme-relearn/configuration/content/linking/index.html#url-management
    disableExplicitIndexURLs = true

[module]
    [[module.imports]]
        path = "github.com/kamar535/hugo-theme-relearn-tweaks"
    [[module.imports]]
        path = "github.com/McShelby/hugo-theme-relearn"

    [[module.mounts]]
        source = 'assets'
        target = 'assets'

    [[module.mounts]]
        source = 'static'
        target = 'assets'

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            #  Whether to render raw HTML mixed within Markdown. This is unsafe unless the content 
            # is under your control. Default is false.
            unsafe = true

        # https://discourse.gohugo.io/t/markdown-images-get-wrong-url/51033/2
        [markup.goldmark.renderHooks.image]
            enableDefault = true

        [markup.goldmark.renderHooks.link]
            enableDefault = true

#  https://gohugo.io/host-and-deploy/host-on-github-pages/#step-5
[caches]
    [caches.images]
        dir = ':cacheDir/images'
