baseURL = 'https://kamar535.github.io/idt-deploy-test.github.io/'

# https://mcshelby.github.io/hugo-theme-relearn/configuration/sitemanagement/deployment/index.html#public-web-server-from-subdirectory
relativeURLs = false

title = 'Introduktion till datorer 2024'

defaultContentLanguage = "sv"
defaultContentLanguageInSubdir = false
# disableDefaultLanguageRedirect = false
disableLanguages = []

# publishDir = "public/2024"

# languageCode = 'en-us'


# publishDir = 'public/2024/'

# Do not set theme here when using modules. 

# theme = 'hugo-theme-relearn'

# theme = ["github.com/theNewDynamic/gohugo-theme-ananke/v2"]

# theme = "PaperMod"


[params]
    # https://github.com/McShelby/hugo-theme-relearn/issues/882
    useDefaultRelref = true
    # https://mcshelby.github.io/hugo-theme-relearn/configuration/content/linking/index.html#url-management
    disableExplicitIndexURLs = true


    # year = 2024

    # Modules on the bottom will get loaded first, so keep anything you don’t want
    # overridden higher up in the module chain. All conflicting files during module
    # import will use the last file loaded. 

    # [module]
    #    [[module.mounts]]
    #        source = "static/images"
    #        target = "static/images/2024"
    # [[module.mounts]]
    # source = "2024/static/images"
    # target = "static/2024/images"
    # [[module.mounts]]
    #    source = "2024/static/terminal"
    #   target = "static/terminal"

[languages]
    [languages.sv]
        contentDir = 'content/swedish'
        languageName = 'Svenska'
        weight = 10
    [languages.en]
        contentDir = 'content/english'
        languageName = 'English'
        weight = 20


[module]
    [[module.imports]]
        path = "github.com/kamar535/hugo-theme-relearn-tweaks"
    [[module.imports]]
        path = "github.com/McShelby/hugo-theme-relearn"

    [[module.mounts]]
        source = 'assets'
        target = 'assets'

    [[module.mounts]]
        source = 'static'
        target = 'assets'


[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            #  Whether to render raw HTML mixed within Markdown. This is unsafe unless the content 
            # is under your control. Default is false.
            unsafe = true

            # https://discourse.gohugo.io/t/markdown-images-get-wrong-url/51033/2
            #     [markup.goldmark.renderHooks.image]
            #        enableDefault = true

            #        [markup.goldmark.renderHooks.link]
            #           enableDefault = true

#  https://gohugo.io/host-and-deploy/host-on-github-pages/#step-5
[caches]
    [caches.images]
        dir = ':cacheDir/images'
